<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Render\FormattableMarkup;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Drupal\Core\StringTranslation\TranslatableMarkup;


/**
 * Implements hook_form_FORM_ID_alter() for agendar_clase node edit form.
 */
function enviar_correo_clase_agendada_gratis_form_agendar_clase_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Agregar un #submit handler personalizado para enviar el correo.
  $form['actions']['submit']['#submit'][] = 'enviar_correo_clase_agendada_gratis_send_email';
}

/**
 * Submit handler para enviar el correo.
 */
function enviar_correo_clase_agendada_gratis_send_email(array &$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  
  // Obtener los valores necesarios del formulario.
  $fecha_clase = $values['field_fecha_de_la_cita']->value;
  $hora_clase = $values['field_hora_de_la_clase']->value;
  $titulo = $values['title']->value;

  // Crear el contenido del correo.
  $message = new FormattableMarkup('<p>Aquí está el archivo invite.ics adjunto para tu clase agendada.</p>', []);
  
  // Obtener el correo del usuario actual.
  $user = \Drupal::currentUser();
  $email = $user->getEmail();
  
  // Generar el archivo invite.ics
  $file_content = 'BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Drupal//Envío de Correo//ES
BEGIN:VEVENT
SUMMARY:' . $titulo . '
DTSTART:' . $fecha_clase . 'T' . $hora_clase . '00
DTEND:' . $fecha_clase . 'T' . $hora_clase . '25
END:VEVENT
END:VCALENDAR';
  
  // Guardar el archivo en la carpeta temporal de Drupal.
  
  $temporary_path = \Drupal::service('file_system')->getTempDirectory() . '/invite.ics';
  
  file_put_contents($temporary_path, $file_content);
  
  // Adjuntar el archivo al correo.
  $attachments[] = $temporary_path;
  
  // Obtener la configuración de correo del sitio.
  $config = \Drupal::config('system.site');
  $site_mail = $config->get('mail');
  
  // Crear el objeto de correo.
  $params['message'] = $message;
  $params['subject'] = 'Invitación a la clase agendada';
  $params['attachments'] = $attachments;
  $params['to'] = $email;
  $params['from'] = $site_mail;
  
  // Enviar el correo.
  $mailManager = \Drupal::service('plugin.manager.mail');
  $result = $mailManager->mail('enviar_correo_clase_agendada_gratis', 'enviar_correo', $email, 'es', $params, NULL, TRUE);
  
  // Verificar si ocurrió un error al enviar el correo.
  if ($result['result'] !== true) {
    // drupal_set_message(t('Hubo un problema al enviar el correo. Por favor, intenta nuevamente más tarde.'), 'error');
    // messenger()->addError(t('Hubo un problema al enviar el correo. Por favor, intenta nuevamente más tarde.'));
    //\Drupal::messenger()->addError(t('Hubo un problema al enviar el correo. Por favor, intenta nuevamente más tarde.'));
     \Drupal::messenger()->addError(new TranslatableMarkup('Hubo un problema al enviar el correo. Por favor, intenta nuevamente más tarde.'));    
  }
}

/**
 * Implementa hook_mail().
 */
function enviar_correo_clase_agendada_gratis_mail($key, &$message, $params) {
  switch ($key) {
    case 'enviar_correo':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      $message['params']['attachments'] = $params['attachments'];
      break;
  }
}