<?php

/**
 * @file
 * Contains \Drupal\create_koalas\Form\CreateKoalasForm.
 */

use Drupal\node\Entity\Node;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\views\ViewExecutable;
use \Drupal\Core\Entity\EntityFormInterface;

/**
 * Implements hook_form_FORM_ID_alter() for the node_agendar_clase_form.
 */
function asignar_profesor_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  
}
/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add views field template suggestions.
 *
 * @inheritdoc
 */
function asignar_profesor_theme_suggestions_views_view_field_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'views_view_field__' . $variables['view']->id();
  // suggestion for field in view
  $suggestions[] = 'views_view_field__' . $variables['view']->id() . '__' . $variables['field']->field;
}




