<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;
use Drupal\Core\Entity\ContentEntityInterface;


/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function custom_user_timezone_user_presave(Drupal\Core\Entity\EntityInterface $entity) {
  // Verifica si se crea un nuevo usuario (no aplicar en actualización de usuarios).
  if ($entity->isNew()) {
    $roles = [];
    if ($entity instanceof User) {
      $roles = $entity->getRoles(); // Obtén los roles del usuario.
    }

    // Verifica si el rol del usuario incluye "padre".
    if (in_array('padre', $roles)) {            
      if ($entity instanceof ContentEntityInterface) {
        $timezone = $entity->get('field_zona_horaria_detectada')->value;
      }
      if ($entity instanceof UserInterface) {
        $entity->set('timezone', $timezone); // Asigna la zona horaria al usuario
      }
    }
  }
}