api_url: 'https://staging-api.pencilapp.com'
authorization_token: AMf-vBwd6Vv1I1JKVNJdATY6igFD_TriuI3Q2718j8N7BPsOH3himbwuMpegL-BAfR7Y31AjbXbtiCXsNZShYe9xKT2YXitu13LJCJXn7B56-yhXcLISS4CzVInoo3rm15qyzcFSYb24n9Gxb5rTr-9iY9bCWfqkKGnX-i245LGAl6ajn9PKw8NSqznJYFE4Ozqsny6nNo1FdOeyNlb_Z6S9IEPyGzk2BeA8f9X-j5ZjwphJ58HjOhrGcVRvErQHnHfF_rl97RRh
