product_bundles:
  4_semanas_mes: 4_semanas_mes
  suscripcion_de_12_semanas: suscripcion_de_12_semanas
  suscripcion_de_24_semanas_: suscripcion_de_24_semanas_
  4_semanas: 0
  default: 0
negate_product_bundles: 0
redirection_route_path: checkout
redirection_route_path_other: ''
add_to_cart_replacement_text: 'Procesar pago'
clear_cart_before_add: 1
