_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  asset_injector: 0
  auto_username: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_pages: 0
  config_translation: 0
  contact: 0
  contextual: 0
  create_koalas: 0
  ctools: 0
  custom_role_redirect: 0
  date_recur: 0
  date_recur_modular: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  fecha_widget: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  form_mode_manager: 0
  form_mode_manager_theme_switcher: 0
  form_mode_user_roles_assign: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  layout_builder: 0
  layout_builder_styles: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  locale: 0
  login_destination: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  multiple_registration: 0
  mysql: 0
  node: 0
  node_view_permissions: 0
  nodeaccess: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  path: 0
  path_alias: 0
  redirect_page_by_role: 0
  registration_role: 0
  responsive_image: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  show_email: 0
  simple_multistep: 0
  simplelogin: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  themable_forms: 0
  timefield: 0
  token: 0
  token_filter: 0
  token_views_filter: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  user_view_mode: 0
  view_mode_select_by_token: 0
  views_extras: 0
  views_templates: 0
  views_tokenized: 0
  views_ui: 0
  xls_serialization: 0
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap_barrio: 0
  bootstrap_barrio_subtheme: 0
  koala: 0
profile: standard
