_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
module:
  add_content_by_bundle: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advanced_text_formatter: 0
  agregar_profesores: 0
  asignar_profesor: 0
  asset_injector: 0
  auto_username: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  calendar_link: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor5: 0
  comment: 0
  computed_field: 0
  config: 0
  config_pages: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  create_koalas: 0
  ctools: 0
  ctools_entity_mask: 0
  custom_child_login: 0
  custom_role_redirect: 0
  date_recur: 0
  date_recur_modular: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  devel_php: 0
  double_field: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_usage: 0
  enviar_correo_clase_agendada_gratis: 0
  fecha_widget: 0
  field: 0
  field_display_label: 0
  field_formatter_class: 0
  field_formatter_filter: 0
  field_group: 0
  field_layout: 0
  field_permissions: 0
  field_ui: 0
  field_validation: 0
  file: 0
  filefield_paths: 0
  filter: 0
  fivestar: 0
  flatpickr_datepicker: 0
  form_mode_control: 0
  form_mode_manager: 0
  form_mode_manager_theme_switcher: 0
  formatter_suite: 0
  fpa: 0
  fullcalendar_view: 0
  help: 0
  history: 0
  html_field_formatter: 0
  iframe: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_checkboxradio: 0
  jquery_ui_controlgroup: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  layout_builder: 0
  layout_builder_styles: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  locale: 0
  login_destination: 0
  mailjet: 0
  mailsystem: 0
  media: 0
  media_library: 0
  media_video_micromodal: 0
  menu_link_content: 0
  menu_token: 0
  menu_ui: 0
  multiple_fields_remove_button: 0
  multiple_registration: 0
  mysql: 0
  node: 0
  node_view_permissions: 0
  nodeaccess: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  path: 0
  path_alias: 0
  readonly_field_widget: 0
  redireccion_front_roles: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  redirect_page_by_role: 0
  registration_role: 0
  responsive_image: 0
  rest: 0
  rules: 0
  search: 0
  serialization: 0
  shortcut: 0
  show_email: 0
  simple_multistep: 0
  simplelogin: 0
  smart_date: 0
  smart_date_calendar_kit: 0
  smart_date_recur: 0
  smart_date_starter_kit: 0
  smtp: 0
  svg_image: 0
  svg_image_responsive: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  time_field: 0
  time_picker: 0
  timefield: 0
  timepicker: 0
  token: 0
  token_filter: 0
  token_views_filter: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  twig_ui: 0
  typed_data: 0
  update: 0
  user: 0
  user_view_mode: 0
  view_mode_select_by_token: 0
  view_password: 0
  views_bootstrap: 0
  views_conditional: 0
  views_extras: 0
  views_templates: 0
  views_tokenized: 0
  views_ui: 0
  votingapi: 0
  votingapi_tokens: 0
  workflows: 0
  xls_serialization: 0
  pathauto: 1
  content_translation: 10
  formdazzle: 10
  views: 10
  twigsuggest: 100
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap_barrio: 0
  bootstrap_barrio_subtheme: 0
  koala: 0
  gin: 0
profile: standard
