_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
langcode: es
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    enabled: true
    expanded: false
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -10
  admin_toolbar_tools__help:
    weight: 1
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_content:
    weight: 2
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  commerce__admin_commerce:
    weight: 3
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_structure:
    weight: 4
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__themes_page:
    weight: 5
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__modules_list:
    weight: 6
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  config_pages__home_padres:
    weight: 7
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_config:
    weight: 8
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  entity__user__collection:
    weight: 10
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_reports:
    weight: 11
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  help__main:
    weight: 12
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
