_core:
  default_config_hash: oS5Qfo4ThgQoDFRG6QjffXGPQFwPKc3CAj6tzbNEN4Q
langcode: es
form_modes:
  node:
    to_exclude:
      administrador: administrador
  user:
    to_exclude:
      registro_basico: registro_basico
  commerce_order_item:
    to_exclude:
      add_to_cart: add_to_cart
  media:
    to_exclude: {  }
  commerce_order:
    to_exclude: {  }
  commerce_subscription:
    to_exclude: {  }
  profile:
    to_exclude: {  }
