type:
  media_media_library: _none
  node_agendar_clases: _none
  node_crear_koalas: _none
  node_editar_agendar_clase_gratis: _none
  user_editar_perfil_padre: _none
  user_editar_profesor: default
  user_registro_de_hijos: _none
  user_registro_de_profesores: _none
  node_asignar_profesor: admin
  node_editar_horarios: admin
  user_register: _none
  commerce_subscription_customer: _none
  node_agendando_clase: _none
  node_cancelar_suscripcion: _none
  node_editar_hijo: _none
  node_editar_metodos_de_pago: _none
  user_agregar_padre: _none
  user_director_colegio: _none
  user_editar_hijo: _none
form_mode:
  media_media_library: null
  node_agendar_clases: null
  node_crear_koalas: null
  node_editar_agendar_clase_gratis: null
  user_editar_perfil_padre: null
  user_editar_profesor: null
  user_registro_de_hijos: null
  user_registro_de_profesores: null
  node_asignar_profesor: null
  node_editar_horarios: null
  user_register: null
  commerce_subscription_customer: null
  node_agendando_clase: null
  node_cancelar_suscripcion: null
  node_editar_hijo: null
  node_editar_metodos_de_pago: null
  user_agregar_padre: null
  user_director_colegio: null
  user_editar_hijo: null
