'use  The form mode default linked to  media entity( audio )': media.audio.default
'use  The form mode media_library linked to  media entity( audio )': media.audio.media_library
'use  The form mode media_library linked to  media entity( avatares_profesores )': media.avatares_profesores.media_library
'use  The form mode media_library linked to  media entity( document )': media.document.media_library
'use  The form mode media_library linked to  media entity( image )': media.image.media_library
'use  The form mode media_library linked to  media entity( remote_video )': media.remote_video.media_library
'use  The form mode media_library linked to  media entity( video )': media.video.media_library
'use  The form mode agendar_clases linked to  node entity( agendar_clase )': node.agendar_clase.agendar_clases
'use  The form mode default linked to  node entity( agendar_clase )': node.agendar_clase.default
'use  The form mode default linked to  node entity( article )': node.article.default
'use  The form mode crear_koalas linked to  node entity( crear_hijos )': node.crear_hijos.crear_koalas
'use  The form mode default linked to  node entity( crear_hijos )': node.crear_hijos.default
'use  The form mode default linked to  node entity( page )': node.page.default
'use  The form mode default linked to  node entity( profesores )': node.profesores.default
'use  The form mode default linked to  user entity( user )': user.user.default
'use  The form mode editar_perfil_padre linked to  user entity( user )': user.user.editar_perfil_padre
'use  The form mode editar_profesor linked to  user entity( user )': user.user.editar_profesor
'use  The form mode register linked to  user entity( user )': user.user.register
'use  The form mode registro_basico linked to  user entity( user )': user.user.registro_basico
'use  The form mode registro_de_hijos linked to  user entity( user )': user.user.registro_de_hijos
'use  The form mode registro_de_profesores linked to  user entity( user )': user.user.registro_de_profesores
'use  The form mode default linked to  block_content entity( basic )': block_content.basic.default
'use  The form mode default linked to  comment entity( comment )': comment.comment.default
'use  The form mode default linked to  config_pages entity( home_padres )': config_pages.home_padres.default
'use  The form mode default linked to  media entity( avatares_profesores )': media.avatares_profesores.default
'use  The form mode default linked to  media entity( document )': media.document.default
'use  The form mode default linked to  media entity( image )': media.image.default
'use  The form mode default linked to  media entity( remote_video )': media.remote_video.default
'use  The form mode default linked to  media entity( video )': media.video.default
'use  The form mode default linked to  taxonomy_term entity( avatar_profesor )': taxonomy_term.avatar_profesor.default
'use  The form mode default linked to  node entity( horarios_de_trabajo )': node.horarios_de_trabajo.default
'use  The form mode administrador linked to  node entity( horarios_de_trabajo )': node.horarios_de_trabajo.administrador
'use  The form mode editar_horarios linked to  node entity( horarios_de_trabajo )': node.horarios_de_trabajo.editar_horarios
'use  The form mode asignar_profesor linked to  node entity( agendar_clase )': node.agendar_clase.asignar_profesor
'use  The form mode default linked to  node entity( agendar_clase_no_gratis )': node.agendar_clase_no_gratis.default
'use  The form mode default linked to  node entity( horarios_profesores )': node.horarios_profesores.default
'use  The form mode default linked to  node entity( event )': node.event.default
'use  The form mode editar_horarios linked to  node entity( horarios_profesores )': node.horarios_profesores.editar_horarios
'use  The form mode agendando_clase linked to  node entity( agendar_clase )': node.agendar_clase.agendando_clase
creation+authenticated+media+audio: media.audio.default
creation+content_editor+media+audio: media.audio.default
creation+administrator+media+audio: media.audio.default
creation+profesor+media+audio: media.audio.default
creation+padre+media+audio: media.audio.default
creation+hijo+media+audio: media.audio.default
modification+authenticated+media+audio: media.audio.default
modification+content_editor+media+audio: media.audio.default
modification+administrator+media+audio: media.audio.default
modification+profesor+media+audio: media.audio.default
modification+padre+media+audio: media.audio.default
modification+hijo+media+audio: media.audio.default
creation+authenticated+media+avatares_profesores: media.avatares_profesores.default
creation+content_editor+media+avatares_profesores: media.avatares_profesores.default
creation+administrator+media+avatares_profesores: media.avatares_profesores.default
creation+profesor+media+avatares_profesores: media.avatares_profesores.default
creation+padre+media+avatares_profesores: media.avatares_profesores.default
creation+hijo+media+avatares_profesores: media.avatares_profesores.default
modification+authenticated+media+avatares_profesores: media.avatares_profesores.default
modification+content_editor+media+avatares_profesores: media.avatares_profesores.default
modification+administrator+media+avatares_profesores: media.avatares_profesores.default
modification+profesor+media+avatares_profesores: media.avatares_profesores.default
modification+padre+media+avatares_profesores: media.avatares_profesores.default
modification+hijo+media+avatares_profesores: media.avatares_profesores.default
creation+authenticated+media+document: media.document.default
creation+content_editor+media+document: media.document.default
creation+administrator+media+document: media.document.default
creation+profesor+media+document: media.document.default
creation+padre+media+document: media.document.default
creation+hijo+media+document: media.document.default
modification+authenticated+media+document: media.document.default
modification+content_editor+media+document: media.document.default
modification+administrator+media+document: media.document.default
modification+profesor+media+document: media.document.default
modification+padre+media+document: media.document.default
modification+hijo+media+document: media.document.default
creation+authenticated+media+image: media.image.default
creation+content_editor+media+image: media.image.default
creation+administrator+media+image: media.image.default
creation+profesor+media+image: media.image.default
creation+padre+media+image: media.image.default
creation+hijo+media+image: media.image.default
modification+authenticated+media+image: media.image.default
modification+content_editor+media+image: media.image.default
modification+administrator+media+image: media.image.default
modification+profesor+media+image: media.image.default
modification+padre+media+image: media.image.default
modification+hijo+media+image: media.image.default
creation+authenticated+media+remote_video: media.remote_video.default
creation+content_editor+media+remote_video: media.remote_video.default
creation+administrator+media+remote_video: media.remote_video.default
creation+profesor+media+remote_video: media.remote_video.default
creation+padre+media+remote_video: media.remote_video.default
creation+hijo+media+remote_video: media.remote_video.default
modification+authenticated+media+remote_video: media.remote_video.default
modification+content_editor+media+remote_video: media.remote_video.default
modification+administrator+media+remote_video: media.remote_video.default
modification+profesor+media+remote_video: media.remote_video.default
modification+padre+media+remote_video: media.remote_video.default
modification+hijo+media+remote_video: media.remote_video.default
creation+authenticated+media+video: media.video.default
creation+content_editor+media+video: media.video.default
creation+administrator+media+video: media.video.default
creation+profesor+media+video: media.video.default
creation+padre+media+video: media.video.default
creation+hijo+media+video: media.video.default
modification+authenticated+media+video: media.video.default
modification+content_editor+media+video: media.video.default
modification+administrator+media+video: media.video.default
modification+profesor+media+video: media.video.default
modification+padre+media+video: media.video.default
modification+hijo+media+video: media.video.default
creation+authenticated+node+agendar_clase: node.agendar_clase.default
creation+content_editor+node+agendar_clase: node.agendar_clase.default
creation+administrator+node+agendar_clase: node.agendar_clase.default
creation+profesor+node+agendar_clase: node.agendar_clase.default
creation+padre+node+agendar_clase: node.agendar_clase.agendando_clase
creation+hijo+node+agendar_clase: node.agendar_clase.default
modification+authenticated+node+agendar_clase: node.agendar_clase.default
modification+content_editor+node+agendar_clase: node.agendar_clase.default
modification+administrator+node+agendar_clase: node.agendar_clase.default
modification+profesor+node+agendar_clase: node.agendar_clase.default
modification+padre+node+agendar_clase: node.agendar_clase.default
modification+hijo+node+agendar_clase: node.agendar_clase.default
creation+authenticated+node+crear_hijos: node.crear_hijos.default
creation+content_editor+node+crear_hijos: node.crear_hijos.default
creation+administrator+node+crear_hijos: node.crear_hijos.default
creation+profesor+node+crear_hijos: node.crear_hijos.default
creation+padre+node+crear_hijos: node.crear_hijos.default
creation+hijo+node+crear_hijos: node.crear_hijos.default
modification+authenticated+node+crear_hijos: node.crear_hijos.default
modification+content_editor+node+crear_hijos: node.crear_hijos.default
modification+administrator+node+crear_hijos: node.crear_hijos.default
modification+profesor+node+crear_hijos: node.crear_hijos.default
modification+padre+node+crear_hijos: node.crear_hijos.default
modification+hijo+node+crear_hijos: node.crear_hijos.default
creation+authenticated+node+horarios_de_trabajo: node.horarios_de_trabajo.default
creation+content_editor+node+horarios_de_trabajo: node.horarios_de_trabajo.default
creation+administrator+node+horarios_de_trabajo: node.horarios_de_trabajo.default
creation+profesor+node+horarios_de_trabajo: node.horarios_de_trabajo.default
creation+padre+node+horarios_de_trabajo: node.horarios_de_trabajo.default
creation+hijo+node+horarios_de_trabajo: node.horarios_de_trabajo.default
modification+authenticated+node+horarios_de_trabajo: node.horarios_de_trabajo.default
modification+content_editor+node+horarios_de_trabajo: node.horarios_de_trabajo.default
modification+administrator+node+horarios_de_trabajo: node.horarios_de_trabajo.default
modification+profesor+node+horarios_de_trabajo: node.horarios_de_trabajo.editar_horarios
modification+padre+node+horarios_de_trabajo: node.horarios_de_trabajo.default
modification+hijo+node+horarios_de_trabajo: node.horarios_de_trabajo.default
creation+authenticated+node+horarios_profesores: node.horarios_profesores.default
creation+content_editor+node+horarios_profesores: node.horarios_profesores.default
creation+administrator+node+horarios_profesores: node.horarios_profesores.default
creation+profesor+node+horarios_profesores: node.horarios_profesores.default
creation+padre+node+horarios_profesores: node.horarios_profesores.default
creation+hijo+node+horarios_profesores: node.horarios_profesores.default
modification+authenticated+node+horarios_profesores: node.horarios_profesores.default
modification+content_editor+node+horarios_profesores: node.horarios_profesores.default
modification+administrator+node+horarios_profesores: node.horarios_profesores.default
modification+profesor+node+horarios_profesores: node.horarios_profesores.default
modification+padre+node+horarios_profesores: node.horarios_profesores.default
modification+hijo+node+horarios_profesores: node.horarios_profesores.default
creation+authenticated+user+user: user.user.default
creation+content_editor+user+user: user.user.default
creation+administrator+user+user: user.user.default
creation+profesor+user+user: user.user.default
creation+padre+user+user: user.user.default
creation+hijo+user+user: user.user.default
modification+authenticated+user+user: user.user.default
modification+content_editor+user+user: user.user.default
modification+administrator+user+user: user.user.default
modification+profesor+user+user: user.user.editar_profesor
modification+padre+user+user: user.user.editar_perfil_padre
modification+hijo+user+user: user.user.default
'use  The form mode default linked to  node entity( mundos )': node.mundos.default
'use  The form mode default linked to  node entity( mundos_detalle )': node.mundos_detalle.default
