_core:
  default_config_hash: ev_QLQNwc0-1EGokxDRzrPpUi1kLXjeBRd5vhwpB6h0
langcode: es
allowed_grant_operations:
  grant_view: true
  grant_update: true
  grant_delete: true
bundles_roles_grants:
  article:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  crear_hijos:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  page:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  agendar_clase:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  profesores:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  horarios_de_trabajo:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  agendar_clase_no_gratis:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  event:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  horarios_profesores:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  mundos:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  mundos_detalle:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  koala_ninos:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  metodos_de_pago:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  clases_estudiantes:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  asignar_clase_a_estudiante:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  suscripciones:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  facturacion_profesor:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  agregar_horarios_de_clases_grati:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  1_fecha_hora_inicio_fin:
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    profesor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    padre:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    hijo:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
grants_tab_availability:
  agendar_clase: false
  profesores: false
  horarios_de_trabajo: false
  agendar_clase_no_gratis: false
  event: false
  horarios_profesores: false
  mundos: false
  mundos_detalle: false
  koala_ninos: false
  metodos_de_pago: false
  clases_estudiantes: false
  asignar_clase_a_estudiante: false
  suscripciones: false
  facturacion_profesor: false
  agregar_horarios_de_clases_grati: false
  1_fecha_hora_inicio_fin: false
map_rid_gid:
  anonymous: 0
  authenticated: 1
  content_editor: 2
  administrator: 3
  profesor: 4
  padre: 5
  hijo: 7
roles_settings:
  anonymous:
    display_name: 'Usuario anónimo'
    name: 'Usuario anónimo'
    weight: 0
    selected: false
  authenticated:
    display_name: 'Usuario autenticado'
    name: 'Usuario autenticado'
    weight: 0
    selected: false
  content_editor:
    display_name: 'Editor de contenido'
    name: 'Editor de contenido'
    weight: 0
    selected: false
  administrator:
    display_name: Administrador
    name: Administrador
    weight: 0
    selected: false
  profesor:
    display_name: Profesor
    name: Profesor
    weight: 0
    selected: false
  padre:
    display_name: Padre
    name: Padre
    weight: 0
    selected: false
  hijo:
    display_name: Hijo
    name: Hijo
    weight: 0
    selected: false
