_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
langcode: es
smtp_on: false
smtp_host: administracion.holakoala.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: admin@administracion.holakoala.com
smtp_password: 'P20625697p*'
smtp_from: admin@administracion.holakoala.com
smtp_fromname: 'Hola Koala'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: pcontramaestre@gmail.com
smtp_reroute_address: admin@administracion.holakoala.com
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
