_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
langcode: es
smtp_on: false
smtp_host: in-v3.mailjet.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: 0a31c796a78b3f8663f85aff18e7da58
smtp_password: 30e7a7f0395f746717eedb29505c3f22
smtp_from: pablo@icreativadigital.com
smtp_fromname: pablo@icreativadigital.com
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: pablo@icreativadigital.com
smtp_reroute_address: pablo@icreativadigital.com
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
