_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: es
uuid: 65502db6-fd91-4d67-bf91-42ac8048fb5d
name: 'Hola Koala'
mail: admin@administracion.holakoala.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
mail_notification: ''
