settings:
  allowed_values:
    -
      label: 'I have found a better deal'
    -
      label: 'This service is too expensive'
    -
      label: 'I would have loved to find more variety of professors'
    -
      label: 'My kid is not learning because the pace of the classes is very fast.'
    -
      label: 'You have very few teaching resources'
    -
      label: 'I just don''t want to continue.'
