display:
  default:
    display_options:
      fields:
        field_fecha_cita_oculta_1:
          alter:
            text: "<p class=\"titulo\">Your next class</p>\r\n<p class=\"fecha\">{{ field_fecha_cita_oculta_1 }}<br>\r\nel {{ field_fecha_cita_oculta }}</p>\r\n<p class=\"enlace\">\r\n<a href=\"/clases?idestudiante={{ field_pencil_id_estudiante }}&url={{ field_pencil_url_clase }}&idClase={{ nid }}\" class=\"editar-clase\"target=\"_blank\">Enter Class</a>\r\n</p>"
