label: 'Redirect Page By Role'
display:
  default:
    display_title: Default
    display_options:
      title: 'Redirect Page By Role'
      fields:
        nid:
          label: Node
        redirect_to:
          label: 'Redirect to'
        role:
          label: Role
        status_code:
          label: 'Status code'
        weight:
          label: Weight
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
  page_1:
    display_title: Page
