display:
  block_1:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row datos-profesor\">\r\n  <div class=\"col-12 text-center titulo-bloque\">\r\n    <h3>Selected teacher for the class</h3>\r\n  </div>\r\n  <div class=\"col-md-3 imagen-profesor\">\r\n    {{ user_picture }}\r\n  </div>\r\n  <div class=\"col-md-9 nombres-profesor\">\r\n    <h2>{{ field_nombres_y_apellidos_del_pr }}</h2>\r\n  </div>\r\n  <div class=\"col-md-12 presentacion-profesor\">\r\n    <p>{{ field_tu_presentacion }}</p>\r\n  </div>\r\n</div>"
  block_2:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row datos-del-koala\">\r\n  <div class=\"col-12 text-center titulo-bloque\">\r\n    <h3>Koala selected for this class</h3>\r\n  </div>\r\n\t<div class=\"col-md-3 imagen-profesor\">\r\n\t\t{{ user_picture }}\r\n\t</div>\r\n\t<div class=\"col-md-9 nombres-profesor\">\r\n\t\t<h2>{{ field_nombre_del_hijo }}</h2>\r\n\t</div>\r\n</div>"
