label: Events
display:
  default:
    display_title: Master
    display_options:
      title: 'Upcoming Events'
      fields:
        title:
          separator: ', '
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      header:
        add_content_by_bundle:
          label: 'Add an Event'
  block_1:
    display_title: Block
    display_options:
      title: 'Upcoming Events'
      fields:
        field_when:
          separator: ', '
        title:
          separator: ', '
      use_more_text: more
  page_1:
    display_title: 'Page - Upcoming'
    display_options:
      menu:
        title: Upcoming
      tab_options:
        title: Events
  page_2:
    display_title: 'Page - Past'
    display_options:
      title: 'Past Events'
      menu:
        title: Past
