label: 'Events Calendar'
display:
  default:
    display_title: Master
    display_options:
      title: 'Events Calendar'
      fields:
        title:
          separator: ', '
        field_when:
          separator: ', '
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      header:
        add_content_by_bundle:
          label: 'Add an Event'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Calendar
