display:
  block_4:
    display_options:
      fields:
        nothing:
          alter:
            text: "  <div class=\"access-acudiente\">\r\n    <div class=\"imagen\"><a href=\"/custom-child-login/{{ field_hijo_relacionado }}\">{{ user_picture }}</a></div>\r\n    <div class=\"nombre-datos\">\r\n      <div class=\"nombre\"><a href=\"/custom-child-login/{{ field_hijo_relacionado }}\">{{ title }}</a></div>\r\n      <div class=\"tipo\"><a href=\"/custom-child-login/{{ field_hijo_relacionado }}\">Student</a></div>\r\n    </div>\r\n  </div>\r\n"
      header:
        area_text_custom:
          content: "<div class=\"text-center mb-4\">\r\n    <strong>Select an account</strong>\r\n</div>\r\n\r\n<a href=\"/padres\" class=\"d-block mb-5\">\r\n<div class=\"access-acudiente\">\r\n  <div class=\"imagen\">{{ user_picture_1 }}</div>\r\n  <div class=\"nombre-datos\">\r\n    <div class=\"nombre\">{{ field_nombre_del_acudiente }}</div>\r\n    <div class=\"tipo\">Parent/Guardian</div>\r\n  </div>\r\n</div>\r\n</a>"
  default:
    display_options:
      footer:
        area_text_custom:
          content: "<a href=\"/node/add/agendar_clase/agendar_clases\" class=\"btn btn-primary mt-5 mb-5\" data-drupal-link-system-path=\"/node/add/agendar_clase/agendar_clases\">Add Koalas</a>\r\n\r\n\r\n"
  attachment_1:
    display_options:
      header:
        area_text_custom:
          content: '<div class="text-center titulo-profesores">Teachers available</div>'
  block_1:
    display_options:
      footer:
        area_text_custom:
          content: "<a href=\"/node/add/agendar_clase/agendar_clases?agregar=1\" class=\"btn btn-primary mt-5 mb-5\" data-drupal-link-system-path=\"/node/add/agendar_clase/agendar_clases\">Add Koalas</a>\r\n\r\n\r\n"
      fields:
        title:
          alter:
            text: "<a href=\"/en/padres/mis-koalas?id={{ field_hijo_relacionado }}\">{{ user_picture }}  <span>{{ title__value }} {{ field_apellidos }}</span></a>\r\n"
  block_2:
    display_options:
      fields:
        nothing_1:
          alter:
            text: "{% set suscripcion_activa = field_suscripcion_activa %}\r\n{% if suscripcion_activa == \"1\" %}\r\n   <div class=\"boton-agendar\"><a href=\"/en/padres/mis-koalas/agendar_clase/{{ nid }}/{{ uid }}\" class=\"agendar-clase btn btn-primary mt-5 mb-5\">Schedule class</a></div>\r\n{% else %}\r\n   <div class=\"boton-agendar\"><a href=\"/node/add/agendar_clase/agendar_clases?escuela=1&uid={{ uid }}\" class=\"agendar-clase btn btn-primary mt-5 mb-5\">Proof class</a></div>\r\n{% endif %}\r\n\r\n<div class=\"boton-agendar boton-editar-nino\"><a href=\"/custom-child-login/{{ nid }}\" class=\"agendar-clase btn btn-primary mt-5 mb-5 entrar-nino\">Enter the child's section</a></div>"
      header:
        area_text_custom:
          content: '<a href="/node/add/agendar_clase/agendar_clases?agregar=1" class="btn btn-primary mt-5 mb-5" data-drupal-link-system-path="/en/node/add/agendar_clase/agendar_clases">Add Koalas</a>'
  block_7_cuadro_koala:
    display_options:
      header:
        area_text_custom:
          content: '<div class="texto-bloque"><h2>Teachers available for</h2></div>'
  page_1:
    display_options:
      footer:
        area_text_custom:
          content: "<a href=\"/en/node/add/agendar_clase/agendar_clases\" id=\"boton-agendamos-clase\" id-estudiante=\"{{ uid|trim }}\" class=\"btn btn-primary mt-5 mb-5\" data-drupal-link-system-path=\"/en/node/add/agendar_clase/agendar_clases\">Next</a>\r\n\r\n\r\n"
  block_6:
    display_options:
      fields:
        nothing:
          alter:
            text: "  <div class=\"access-acudiente\">\r\n    <div class=\"imagen\"><a href=\"/en/padres/mis-koalas/agendar_clase/{{ nid }}/{{ uid }}\">{{ user_picture }}</a></div>\r\n    <div class=\"nombre-datos\">\r\n      <div class=\"nombre\"><a href=\"/en/padres/mis-koalas/agendar_clase/{{ nid }}/{{ uid }}\">{{ title }}</a></div>\r\n      <div class=\"tipo\"></div>\r\n    </div>\r\n  </div>\r\n"
        title:
          alter:
            text: "<a href=\"/en/padres/mis-koalas/agendar_clase/{{ nid }}/{{ uid }}\">{{ title__value }}</a>\r\n"
      header:
        area_text_custom:
          content: '<div class="text-center mt-4 mb-5">Who do you want to schedule?</div>'
  block_3:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          text_input_required: 'Choose a date and click apply to see the teachers available on the selected day.'
      filters:
        field_fechas_laborables_value:
          expose:
            label: 'Select date'
            description: 'Select a date range to search for available teachers'
            min_placeholder: 'Since the date'
            max_placeholder: 'Till the date'
  profesor_detalle_horario:
    display_options:
      title: 'Search teachers'
  block_5:
    display_options:
      fields:
        nothing:
          alter:
            text: "{{ nothing_1 }}\r\n<div class=\"datos-clase\">\r\n  <div class=\"imagen\">\r\n\r\n  </div>\r\n  <div class=\"alumno text-center\">\r\n    <p>Student</p>\r\n    <div class=\"datos-alumno\">\r\n      <img src=\"{{ user_picture }}\" class=\"mw-100\">\r\n      {{ field_nombre_del_nino_a }} \r\n    </div>\r\n  </div>\r\n  <div class=\"profesor text-center\">\r\n    <p>Teacher</p>\r\n    <div class=\"datos-profesor\">\r\n      {{ user_picture_1 }}\r\n       {{ field_nombres_y_apellidos_del_pr }} \r\n    </div>\r\n  </div>\r\n  <div class=\"fecha text-center\">\r\n    <p>Date</p>\r\n    <div class=\"fecha\">{{ field_fecha_cita_oculta_1 }}</div>\r\n  </div>\r\n  <div class=\"boton\">\r\n        <a href=\"/en/clases?idestudiante={{ field_pencil_id_estudiante }}&url={{ field_pencil_url_clase }}&idClase={{ nid }}\" class=\"editar-clase\"target=\"_blank\">Go to class</a>\r\n   </div>\r\n   {{ field_tipo_clase }}\r\n</div>"
        field_tipo_clase:
          alter:
            text: "{% set tipo_de_clase = field_tipo_clase__value %}\r\n{% if tipo_de_clase == \"Gratis\" %}\r\n  <div class=\"editar-horario\"><a href=\"/en/cancelar-clase-gratis/{{ uid }}/{{ nid }}\" class=\"cancelar-clase\" id=\"cancelarclase\">Reschedule class</a></div>\r\n{% else %}\r\n  <div class=\"editar-horario\"><a href=\"/en/cancelar-clase?id={{ nid }}\" class=\"cancelar-clase\" id=\"cancelarclase\" data-url=\"/en/cancelar-clase?id={{ nid }}\">Cancel</a></div>\r\n{% endif %}"
label: 'My Koalas'
