display:
  block_1:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"koalas-profes d-flex\">\r\n  <a href=\"/en/profesor/mis-koalas?id={{ uid }}\" class=\"d-flex w-100 enlaces-koalas\">\r\n   <div class=\"imagen\">{{ user_picture }}</div>\r\n   <div class=\"nombre-koala\">{{ field_nombre_del_hijo }}</div>\r\n  </a>\r\n</div>"
      footer:
        area_text_custom:
          content: '<div class="ver-todos-koalas"><a href="/en/profesor/mis-koalas">See all my koalas</a></div>'
  block_2:
    display_options:
      header:
        area_text_custom:
          content: '<div class="titulo text-center mt-4 mb-4 p-3"><h3>My Koalas</h3></div>'
  default:
    display_options:
      header:
        area_text_custom:
          content: "<div class=\"titulo-vista\">Progress of my Koalas</div>\r\n<div class=\"descripcion-vista\">Know the progress of each student and prepare your next class</div>"
      footer:
        area_text_custom:
          content: '<div class="ver-todos-koalas"><a href="#">See all my koalas</a></div>'
